//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDSHDEntities : DbContext
    {
        public BDSHDEntities()
            : base("name=BDSHDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlbumImage> AlbumImages { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<CategoryPost> CategoryPosts { get; set; }
        public virtual DbSet<CategoryProject> CategoryProjects { get; set; }
        public virtual DbSet<Duong> Duongs { get; set; }
        public virtual DbSet<HoSoPhapLyBD> HoSoPhapLyBDS { get; set; }
        public virtual DbSet<HuongBD> HuongBDS { get; set; }
        public virtual DbSet<Huyen> Huyens { get; set; }
        public virtual DbSet<ImageBanner> ImageBanners { get; set; }
        public virtual DbSet<ImageProject> ImageProjects { get; set; }
        public virtual DbSet<ImageTinBD> ImageTinBDS { get; set; }
        public virtual DbSet<InfoCompany> InfoCompanies { get; set; }
        public virtual DbSet<ItemAlbumImage> ItemAlbumImages { get; set; }
        public virtual DbSet<KhoangTienBD> KhoangTienBDS { get; set; }
        public virtual DbSet<LoaiBD> LoaiBDS { get; set; }
        public virtual DbSet<MucDichBD> MucDichBDS { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<TinBD> TinBDS { get; set; }
        public virtual DbSet<Tinh> Tinhs { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<Xa> Xas { get; set; }
    }
}
