//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinBD
    {
        public int Id { get; set; }
        public string MaBDS { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> TinhId { get; set; }
        public Nullable<int> HuyenId { get; set; }
        public Nullable<int> XaId { get; set; }
        public Nullable<int> DuongId { get; set; }
        public string LoaiBDSId { get; set; }
        public string HuongBDSId { get; set; }
        public string MucDichBDSId { get; set; }
        public string HoSoPhapLyBDSId { get; set; }
        public string KhoangTienBDSId { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<double> DienTichDat { get; set; }
        public bool Published { get; set; }
        public bool Featured { get; set; }
        public string Image { get; set; }
        public string TenNguoiLH { get; set; }
        public string DiaChiLH { get; set; }
        public string DienThoaiLH { get; set; }
        public string EmailLH { get; set; }
        public string Note { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKewords { get; set; }
        public string Author { get; set; }
        public string Robots { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public string UserId { get; set; }
        public double Views { get; set; }
    }
}
